--- #YAML:1.0
name:                Statistics-Benford
version:             0.01
abstract:            calculate the deviation from Benford's Law
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    List::Util:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - gray <gray@cpan.org>
