--- #YAML:1.0
name:               Statistics-Benford
version:            0.07
abstract:           calculate the deviation from Benford's Law
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    List::Util:  0
    Test::More:  0
resources:
    repository:  http://github.com/gray/statistics-benford
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
